
title: Nova's Workshop
author:
  name: Wei Zhang
description: >- # this means to ignore newlines until "baseurl:"
    Free will  
markdown: kramdown
kramdown:
    math_engine: katex
    parse_block_html: true

permalink: /:categories/:title
google_analytics: UA-223008037-1

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/noblegasss/" }
    - { platform: linkedin, user_url: "http://linkedin.com/in/nova-weizhang" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=BRtsZUAAAAAJ&hl=en" }


# Build settings
remote_theme: "jekyll/minima@1e8a445"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
